name: 'inventoria-prod'
services:
  minio:
    image: quay.io/minio/minio
    container_name: s3-prod
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web UI
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword
    restart: unless-stopped

  mc:
    image: minio/mc
    container_name: s3-client-prod
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 && \
        mc alias set s3 http://s3-prod:9000 minio miniopassword && \
        mc mb -p s3/inventoria && \
        echo '✅ Bucket created: inventoria' || echo '⚠️ Bucket may already exist'
      "
    restart: 'no'

  mongo:
    image: mongo
    container_name: mongo-prod
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
    restart: unless-stopped
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo-init:
    image: mongo
    container_name: mongo-init-prod
    depends_on:
      - mongo
    restart: 'no'
    entrypoint: >
      bash -c "
        sleep 5 && \
        mongosh --host mongo --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          })
        ' || echo '✅ Replica set may already be initialized.'
      "

  backend:
    image: szaki/inventoria-backend
    container_name: inventoria-backend-prod
    ports:
      - '3001:3000' # exposed as 3001 externally
    depends_on:
      - mongo
      - minio
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: szaki/inventoria-frontend
    container_name: inventoria-frontend-prod
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
