/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as ItemsAddRouteImport } from './routes/items/add'
import { Route as LocationsLocationIndexRouteImport } from './routes/locations/$location/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsAddRoute = ItemsAddRouteImport.update({
  id: '/items/add',
  path: '/items/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIndexRoute = LocationsLocationIndexRouteImport.update({
  id: '/locations/$location/',
  path: '/locations/$location/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items/add': typeof ItemsAddRoute
  '/locations': typeof LocationsIndexRoute
  '/locations/$location': typeof LocationsLocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items/add': typeof ItemsAddRoute
  '/locations': typeof LocationsIndexRoute
  '/locations/$location': typeof LocationsLocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items/add': typeof ItemsAddRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$location/': typeof LocationsLocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items/add' | '/locations' | '/locations/$location'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items/add' | '/locations' | '/locations/$location'
  id: '__root__' | '/' | '/items/add' | '/locations/' | '/locations/$location/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsAddRoute: typeof ItemsAddRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsLocationIndexRoute: typeof LocationsLocationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/add': {
      id: '/items/add'
      path: '/items/add'
      fullPath: '/items/add'
      preLoaderRoute: typeof ItemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$location/': {
      id: '/locations/$location/'
      path: '/locations/$location'
      fullPath: '/locations/$location'
      preLoaderRoute: typeof LocationsLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsAddRoute: ItemsAddRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsLocationIndexRoute: LocationsLocationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
